#!/usr/bin/env python
# -*- coding: utf-8 -*-

####
# 05/2008 Alexander Atemenko <svetlyak.40wt@gmail.com>
#
# Special thanks to:
# Grigory Bakunov <bobuk@justos.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import getpass
import itertools
import logging
import os
import sys
from yafotki.required import OptionParser, Option
from optparse import OptionGroup, IndentedHelpFormatter, SUPPRESS_USAGE
from functools import wraps

from pdb import set_trace

import yafotki

CONFIG_PATH = os.path.expanduser('~/.fotki.conf')
TOKEN_CACHE = os.path.expanduser('~/.fotki.token')

class Config(object):
    '''Simple config loader with singleton instance'''
    _shared = {
        '_loaded': False,
        'access_type': 'public',
        'disable_comments': 'no',
        'xxx': 'no',
        'hide_original': 'no',
        'storage_private': 'no',
        'yaru': 'yes',
    }

    def __init__(self):
        self.__dict__ = self._shared
        if not self._loaded:
            if os.path.exists(CONFIG_PATH):
                cfg = open(CONFIG_PATH)
                for line in (x.strip() for x in cfg.readlines()):
                    if '=' not in line:
                        [key, value] = [line, True]
                    else:
                        [key, value] = [x.strip() for x in line.split('=')]
                    setattr(self, key, value)
                cfg.close()
                self._loaded = True

    def update(self, opts):
        for key in dir(opts):
            if not key.startswith('_'):
                value = getattr(opts, key)
                if not hasattr(value, '__call__') and value:
                    setattr(self, key, value)

    def __getattr__(self, name):
        return None

    def __repr__(self):
        return repr(self.__dict__)

def auth_required(func):
    @wraps(func)
    def wrap(self, *args, **kwargs):
        if not self.api.token:
            logging.error('Please use "auth" command to authorize on the service.')
            sys.exit(1)
        return func(self, *args, **kwargs)
    return wrap


class Uploader(object):
    def __init__(self):
        self.config = Config()

        self.api = yafotki.Api()

        if os.path.exists(TOKEN_CACHE):
            f = open(TOKEN_CACHE)
            self.api.token = f.readline()
            f.close()

    def auth(self, global_opts, global_args,
                  command_opts, command_args):
        logging.debug('getting new authentication token')

        if self.config.username is None:
            logging.error('Please supply username via '
                          '--username option or in the config.')
            sys.exit(0)

        password = self.config.password or \
                   getpass.getpass('Input password: ')

        self.api.auth(self.config.username, password)
        f = open(TOKEN_CACHE, 'w+')
        f.write(self.api.token)
        f.close()
        print 'New token was written to %r' % TOKEN_CACHE

    @auth_required
    def upload(self, global_opts, global_args,
               command_opts, command_args):
        try:
            user = self.api.find_user(self.config.username)
            user.albums[command_opts.album - 1].upload(
                command_args,
                title = self.config.title,
                tags = self.config.tags,
                description = self.config.description,
                access_type = yafotki.ACCESS.fromstring(self.config.access_type),
                disable_comments = self.config.disable_comments,
                xxx = self.config.xxx,
                hide_orig = self.config.hide_original,
                storage_private = self.config.storage_private,
                yaru = self.config.yaru,
            )
        except IndexError:
            logging.error('Wrong album number.')
            sys.exit(1)

    def get_albums(self, global_opts, global_args,
                   command_opts, command_args):
        user = self.api.find_user(self.config.username)
        self._print_albums(user.albums)

    def get_photos(self, global_opts, global_args,
                   command_opts, command_args):
        user = self.api.find_user(self.config.username)
        if command_opts.album is not None:
            album = user.albums[command_opts.album - 1]
            photos = album.photos
            print 'Album "%s"' % album.title
        else:
            photos = user.photos
            print '%s photos' % user.username

        for i, photo in enumerate(photos):
            print '%i) "%s"' % (i+1, photo.title)

    def _print_albums(self, albums):
        for i, album in enumerate(albums):
            if album.image_count:
                image_count = '%d image(s)' % album.image_count
            else:
                image_count = 'empty'

            if self.config.verbose:
                print '%i) "%s", real id "%s", %s' % \
                    (i+1, album.title, album.id, image_count)
            else:
                print '%i) "%s", %s' % (i+1, album.title, image_count)

    @auth_required
    def create_album(self, global_opts, global_args,
                     command_opts, command_args):
        user = self.api.find_user(self.config.username)
        user.create_album(command_opts.title, command_opts.summary)

    @auth_required
    def delete_album(self, global_opts, global_args,
                     command_opts, command_args):
        user = self.api.find_user(self.config.username)
        user.albums[command_opts.album - 1].delete()

    @auth_required
    def delete_photo(self, global_opts, global_args,
                     command_opts, command_args):
        user = self.api.find_user(self.config.username)
        album = user.albums[command_opts.album - 1]
        album.photos[command_opts.photo - 1].delete()

    @auth_required
    def modify_album(self, global_opts, global_args,
                     command_opts, command_args):
        user = self.api.find_user(self.config.username)
        album = user.albums[command_opts.album - 1]
        self._save_object(album, command_opts)

    @auth_required
    def modify_photo(self, global_opts, global_args,
                     command_opts, command_args):
        user = self.api.find_user(self.config.username)
        album = user.albums[command_opts.album - 1]
        photo = album.photos[command_opts.photo - 1]
        self._save_object(photo, command_opts)

    def _save_object(self, obj, update_from):
        for field in obj.fields:
            value = getattr(update_from, field, None)
            if value is not None:
                setattr(obj, field, value.decode('UTF8'))
        obj.save()

class MyHelpFormatter(IndentedHelpFormatter):
    def __init__(self, heading):
        self.heading = heading
        IndentedHelpFormatter.__init__(self)

    def format_heading(self, heading):
        return '%*s%s:\n' % (self.current_indent, "", self.heading)

def main():
    config = Config()

    global_parser = OptionParser(
        usage = 'usage: %prog [global options] command [command options] [args]',
        option_list = [
            Option('-h', '--help', dest='help', action='store_true',
                    help='Print help and exit.', default=False),
            Option('-v', '--verbose', dest='verbose', action='store_true',
                    help='Output more information.', default=False),
            Option('--version', dest='version', action='store_true',
                    help='Show version number and quit.', default=False),
            Option('--token', dest='token', help='Auth token.', default=None),
        ],
        add_help_option = False,
        formatter = MyHelpFormatter('Global options')
    )

    empty_parser = OptionParser()

    auth_parser = OptionParser(
        option_list = [
            Option('-u', '--user', dest='username',
                   help='Your login.'),
            Option('-p', '--pass', dest='password',
                   help='Your password.')
        ],
        usage = SUPPRESS_USAGE,
        add_help_option = False,
        formatter = MyHelpFormatter("Command 'auth'")
    )

    create_album_parser = OptionParser(
        option_list = [
            Option('-t', '--title', dest='title',
                   help='Album\'s title.', required = True),
            Option('-s', '--summary', dest='summary',
                   help='Short description.')
        ],
        usage = SUPPRESS_USAGE,
        add_help_option = False,
        formatter = MyHelpFormatter("Command 'create-album'")
    )

    delete_album_parser = OptionParser(
        option_list = [
            Option('-a', '--album', dest='album', type='int',
                   help='Album\'s number.', required = True),
        ],
        usage = SUPPRESS_USAGE,
        add_help_option = False,
        formatter = MyHelpFormatter("Command 'delete-album'")
    )

    delete_photo_parser = OptionParser(
        option_list = [
            Option('-a', '--album', dest='album', type='int',
                   help='Album\'s number.', required = True),
            Option('-p', '--photo', dest='photo', type='int',
                   help='Photo\'s number.', required = True),
        ],
        usage = SUPPRESS_USAGE,
        add_help_option = False,
        formatter = MyHelpFormatter("Command 'delete-photo'")
    )

    photos_parser = OptionParser(
        option_list = [
            Option('-a', '--album', dest='album', type='int',
                   help='Album\'s number.'),
        ],
        usage = SUPPRESS_USAGE,
        add_help_option = False,
        formatter = MyHelpFormatter("Command 'photos'")
    )

    modify_album_parser = OptionParser(
        option_list = [
            Option('-a', '--album', dest='album', type='int',
                   help='Album\'s number.', required = True),
            Option('-t', '--title', dest='title',
                   help='Album\'s title.'),
            Option('-s', '--summary', dest='summary',
                   help='Short description.')
        ],
        usage = SUPPRESS_USAGE,
        add_help_option = False,
        formatter = MyHelpFormatter("Command 'modify-album'")
    )

    photo_options = [
        Option('-t', '--title', dest='title',
               help='Image\'s title (by default it will be extracted from exif).'),
        Option('-k', '--tags', dest='tags',
               help='Comma separated tags/keywords (by default it will be extracted from exif).'),
        Option('-d', '--description', dest='description',
               help='Short description (by default it will be extracted from exif).'),
        Option('--access', dest='access_type',
               help='String value, one from the following list: ['
                    '"public", "friends", "private"] (default %default).',
               default=config.access_type),
        Option('--no-comments', dest='disable_comments',
               help='Disable comments, "yes" or "no" (default %default)).',
               default=config.disable_comments),
        Option('-x', '--xxx', dest='xxx',
               help='Content for adults only, "yes" or "no" (default %default)).',
               default=config.xxx),
        Option('--hide-original', dest='hide_original',
               help='Hide original image from other users, "yes" or "no" (default %default)).',
               default=config.hide_original),
        Option('--storage-private', dest='storage_private',
               help='Disable image downloadig from other sources, "yes" or "no" (default %default)).',
               default=config.storage_private),
        Option('-y', '--to-yaru', dest='yaru',
               help='Publish on i.ya.ru, "yes" or "no" (default %default)).',
               default=config.yaru),
    ]

    upload_parser = OptionParser(
        option_list = [
            Option('-a', '--album', type='int', dest='album',
                   help='Album\'s number.', required=True),
        ] + photo_options,
        add_help_option = False,
        usage = SUPPRESS_USAGE,
        formatter = MyHelpFormatter("Command 'upload'")
    )

    modify_photo_parser = OptionParser(
        option_list = [
            Option('-a', '--album', dest='album', type='int',
                   help='Album\'s number.', required = True),
            Option('-p', '--photo', dest='photo', type='int',
                   help='Photo\'s number.', required = True),
        ] + photo_options,
        usage = SUPPRESS_USAGE,
        add_help_option = False,
        formatter = MyHelpFormatter("Command 'modify-album'")
    )

    uploader = Uploader()

    commands = [
        ('albums', empty_parser, uploader.get_albums),
        ('auth', auth_parser, uploader.auth),
        ('upload', upload_parser, uploader.upload),
        ('create-album', create_album_parser, uploader.create_album),
        ('delete-album', delete_album_parser, uploader.delete_album),
        ('modify-album', modify_album_parser, uploader.modify_album),
        ('photos', photos_parser, uploader.get_photos),
        ('delete-photo', delete_photo_parser, uploader.delete_photo),
        ('modify-photo', modify_photo_parser, uploader.modify_photo),
    ]
    args = sys.argv

    def print_help():
        global_parser.print_help()
        for command, parser, func in commands:
            if parser != empty_parser:
                parser.print_help()

    for command, parser, callback in commands:
        if command in args:
            idx = args.index(command)
            glob_opts, glob_args = global_parser.parse_args(args[:idx])
            cmd_opts, cmd_args = parser.parse_args(args[idx+1:])
            break
    else:
        print_help()
        sys.exit(1)

    if glob_opts.verbose:
        logging.basicConfig(level = logging.DEBUG, format = '%(message)s')
    else:
        logging.basicConfig(level = logging.WARNING, format = '%(message)s')

    if glob_opts.version:
        logging.error('Python uploader for http://fotki.yandex.ru, version %s.' % yafotki.VERSION)
        logging.error('For more information and new versions, visit http://svetlyak.ru.')
        sys.exit(0)

    config.update(glob_opts)
    config.update(cmd_opts)
    logging.debug('Config values %r' % config)

    callback(glob_opts, glob_args, cmd_opts, cmd_args)

if __name__ == "__main__":
    main()
    sys.exit(0)

